language: python
python:
  - 3.7
cache: pip
install:
  - pip install -r requirements.txt
before_script:
  - python -m rasa_nlu.train -c config.yml --data data/nlu.md --fixed_model_name test
script:
  - python test.py
